# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: en
reviews:
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  path_filters:
    - "!**/resources/**"
  high_level_summary: true
  poem: false

