org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version_range=[1.21.1]
loader_version_range=[1,)
ae2_version_range=[19.2.17,)

extra_mods=false

apotheosisVersion=8.4.2
patchouliVersion=1.21-87-NEOFORGE
pufferfishsSkillsVersion=0.17.2+1.21
pufferfishsAttributesVersion=0.8.2+1.21
irons_spells_version=3.15.3
player_animator_version=2.0.1+1.21.1
geckolib_version=4.7.5.1
irons_jewelry_version=1.6.0
atlas_api_version=1.2.0
accessories_version=1.1.0-beta.53+1.21.1

mod_id=incore
mod_name=INCore
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=io.github.ozokuz.incore
